# Generated by Django 4.2.2 on 2024-08-22 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Год")),
                ("month", models.PositiveSmallIntegerField(verbose_name="Месяц")),
            ],
            options={
                "verbose_name": "График работы",
                "verbose_name_plural": "Графики работ",
                "ordering": ["-month"],
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата смены")),
                (
                    "morning_needed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество сотрудников в утро"
                    ),
                ),
                (
                    "day_needed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество сотрудников в день"
                    ),
                ),
                (
                    "night_needed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество сотрудников в ночь"
                    ),
                ),
                (
                    "assigned_employees",
                    models.ManyToManyField(
                        blank=True,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Назначенные сотрудники",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.schedule",
                        verbose_name="График работы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Смена",
                "verbose_name_plural": "Смены",
                "ordering": ["-date"],
            },
        ),
    ]
