# Generated by Django 4.2.2 on 2024-08-28 07:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_schedule_shift"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employeewish",
            options={
                "verbose_name": "Пожелание сотрудника",
                "verbose_name_plural": "Пожелания сотрудников",
            },
        ),
        migrations.AddField(
            model_name="employeewish",
            name="comment",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="employeewish",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
    ]
