# Generated by Django 4.2.2 on 2024-08-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0003_alter_employeewish_options_employeewish_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeewish",
            name="comment",
            field=models.TextField(
                blank=True, max_length=155, null=True, verbose_name="Комментарий"
            ),
        ),
    ]
