# Generated by Django 4.2.2 on 2024-08-28 23:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0004_alter_employeewish_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schedule",
            options={
                "ordering": ["-date"],
                "verbose_name": "График работы",
                "verbose_name_plural": "Графики работ",
            },
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="month",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="year",
        ),
        migrations.AddField(
            model_name="schedule",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Дата"
            ),
            preserve_default=False,
        ),
    ]
