# Generated by Django 4.2.2 on 2024-09-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0006_vacation"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="is_calculated",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="График рассчитан"
            ),
        ),
    ]
