# Generated by Django 4.2.2 on 2024-09-28 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schedule", "0007_schedule_is_calculated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shift",
            name="assigned_employees",
        ),
        migrations.CreateModel(
            name="ShiftAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shift_type",
                    models.CharField(
                        choices=[
                            ("morning", "Утро"),
                            ("day", "День"),
                            ("night", "Ночь"),
                            ("free", "Выходной"),
                        ],
                        max_length=20,
                        verbose_name="Тип смены",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.shift",
                        verbose_name="Смена",
                    ),
                ),
            ],
            options={
                "unique_together": {("shift", "employee")},
            },
        ),
    ]
